trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  # This token should be stored securely in Azure DevOps Library as a secret variable
  azure_static_web_apps_api_token: 22695afe0c6ee7ac70e77d903d32a49a164e28c203617b48fe3be349cabef45806-77aa3431-e4e4-43e7-9ba7-456f42c8824c01029120ea91e410

stages:
  - stage: BuildAndDeploy
    displayName: Build and Deploy to Azure Static Web Apps
    jobs:
      - job: BuildAndDeployJob
        displayName: Build and Deploy Job
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Install dependencies and build project'

          - task: AzureStaticWebApp@0
            inputs:
              app_location: '/'                 # Root folder for React app
              output_location: 'build'          # React build output folder
              api_location: ''                  # Leave blank if no API
              azure_static_web_apps_api_token: '$(azure_static_web_apps_api_token)'
            displayName: 'Deploy to Azure Static Web Apps'
