trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  # This token should be stored securely in Azure DevOps Library as a secret variable
  azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)

stages:
  - stage: BuildAndDeploy
    displayName: Build and Deploy to Azure Static Web Apps
    jobs:
      - job: BuildAndDeployJob
        displayName: Build and Deploy Job
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Install dependencies and build project'

          - task: AzureStaticWebApp@0
            inputs:
              app_location: '/'                 # Root folder for React app
              output_location: 'build'          # React build output folder
              api_location: ''                  # Leave blank if no API
              azure_static_web_apps_api_token: '$(azure_static_web_apps_api_token)'
            displayName: 'Deploy to Azure Static Web Apps'
